#!/usr/bin/env bash

# Now let's echo a bunch of stuff

# Single quoting effect with double exclamation point
echo '!sudo'

# Conditionals that may echo single quoted strings containing !
[ a == a ] && echo '!sudo'
[ a != a ] && echo '!sudo'
[ a == a ] || echo '!sudo'
[ a != a ] || echo '!sudo'
[[ a == a ]] && echo '!sudo'
[[ a != a ]] && echo '!sudo'
[[ a == a ]] || echo '!sudo'
[[ a != a ]] || echo '!sudo'
if true; then echo '!sudo'; fi
if false; then echo '!sudo'; fi
while false; do echo '!sudo' && break; done
while true; do echo '!sudo' && break; done
until false; do echo '!sudo' && break; done
until true; do echo '!sudo' && break; done
case a in a) echo '!sudo'; esac
case a in b) echo '!sudo'; esac
case a in a) echo '!sudo';; esac
case a in b) echo '!sudo';; esac
case a in a) echo '!sudo';;& esac
case a in b) echo '!sudo';;& esac

# Now in comsubs
echo $([ a == a ] && echo '!sudo')
echo $([ a != a ] && echo '!sudo')
echo $([ a == a ] || echo '!sudo')
echo $([ a != a ] || echo '!sudo')
echo $([[ a == a ]] && echo '!sudo')
echo $([[ a != a ]] && echo '!sudo')
echo $([[ a == a ]] || echo '!sudo')
echo $([[ a != a ]] || echo '!sudo')
echo $(if true; then echo '!sudo'; fi)
echo $(if false; then echo '!sudo'; fi)
echo $(while false; do echo '!sudo' && break; done)
echo $(while true; do echo '!sudo' && break; done)
echo $(until false; do echo '!sudo' && break; done)
echo $(until true; do echo '!sudo' && break; done)
echo $(case a in a) echo '!sudo'; esac)
echo $(case a in b) echo '!sudo'; esac)
echo $(case a in a) echo '!sudo';; esac)
echo $(case a in b) echo '!sudo';; esac)
echo $(case a in a) echo '!sudo';;& esac)
echo $(case a in b) echo '!sudo';;& esac)

# Now in quoted comsubs
echo "$([ a == a ] && echo '!sudo')"
echo "$([ a != a ] && echo '!sudo')"
echo "$([ a == a ] || echo '!sudo')"
echo "$([ a != a ] || echo '!sudo')"
echo "$([[ a == a ]] && echo '!sudo')"
echo "$([[ a != a ]] && echo '!sudo')"
echo "$([[ a == a ]] || echo '!sudo')"
echo "$([[ a != a ]] || echo '!sudo')"
echo "$(if true; then echo '!sudo'; fi)"
echo "$(if false; then echo '!sudo'; fi)"
echo "$(while false; do echo '!sudo' && break; done)"
echo "$(while true; do echo '!sudo' && break; done)"
echo "$(until false; do echo '!sudo' && break; done)"
echo "$(until true; do echo '!sudo' && break; done)"
echo "============================================"
echo "$(case a in a) echo '!sudo'; esac)"
echo "$(case a in b) echo '!sudo'; esac)"
echo "$(case a in a) echo '!sudo';; esac)"
echo "$(case a in b) echo '!sudo';; esac)"
echo "$(case a in a) echo '!sudo';;& esac)"
echo "$(case a in b) echo '!sudo';;& esac)"

# This proves that it's specific to case statements inside COMSUB
# while running in interactive mode, and is not a more general result
# of us misusing '!' or having some shell feature enabled that causes
# bash to behave differently in interactive mode. All the conditionals
# above are fine except the case statements.

