#!/usr/bin/env bash

# BASH BUG: Run this file four times
# 1. sh BASH_BUG
# 2. sh -i BASH_BUG
# 3. bash BASH_BUG
# 4. bash -i BASH_BUG
# Runs 1 and 2 are just to check that the syntax is valid posix shell.
# Runs 3 and 4 examine bash itself, specifically interactive mode.
# In case 4, certain COMM_SUBs cause an error in the parser.


# simple echo of a single quoted string with an exclamation point in it:
# (1) raw
# (2) in comsub
# (3) in double quoted comsub
echo "BLOCK 1: No errors"
echo 'hi!'
echo $(echo 'hi!')
echo "$(echo 'hi!')"
echo

# now consider the following more complex echo of a single quoted string with an exclamation point in it:
# (1) raw
# (2) in comsub
# (3) in double quoted comsub
echo "BLOCK 2: Error on the third command"
case a in a) echo 'hi!';; esac
echo $(case a in a) echo 'hi!';; esac)
echo "$(case a in a) echo 'hi!';; esac)"
echo

# the error occurs even if the string in question is not echoed
# but only when the comsub is quoted, and only when bash is running
# interactively
echo "BLOCK 3: Error even when not echoing the problematic string"
case a in b) echo 'hi!';; esac
echo $(case a in b) echo 'hi!';; esac)
echo "$(case a in b) echo 'hi!';; esac)"
echo


# Here are the same six commands when 'hi!' is not quoted
echo "BLOCK 4: No errors when the inner string is unquoted"
case a in a) echo hi!;; esac
echo $(case a in a) echo hi!;; esac)
echo "$(case a in a) echo hi!;; esac)"
case a in b) echo hi!;; esac
echo $(case a in b) echo hi!;; esac)
echo "$(case a in b) echo hi!;; esac)"
echo

echo "BLOCK 5: We get a different error when the inner string is double quoted"
case a in a) echo "hi!";; esac
echo $(case a in a) echo "hi2!";; esac)
echo "$(case a in a) echo "hi!";; esac)"
case a in b) echo "hi!";; esac
echo $(case a in b) echo "hi!";; esac)
echo "$(case a in b) echo "hi!";; esac)"
echo

echo "BLOCK 6: What if the exclamation point isn't at the end?"
case a in a) echo "hi!1";; esac
echo $(case a in a) echo "hi!2";; esac)
echo "$(case a in a) echo "hi!3";; esac)"
case a in b) echo "hi!4";; esac
echo $(case a in b) echo "hi!5";; esac)
echo "$(case a in b) echo "hi!6";; esac)"
echo
